title: Kubeflow series
author: Rishit Dagli
email: rishit.dagli@gmail.com
description: >
  The blog series where we to try to understand how Kubeflow works as well as using it throughout the Machine Learning workflow. A backup of the Kubeflow series on Kubesimplify.com .
# social links
twitter_username: rishit_dagli # DO NOT include the @ character, or else the build will fail!
github_username:  Rishit-dagli # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima